#############################################################################
# Makefile for building: KeyCoin-qt
# Generated by qmake (2.01a) (Qt 4.8.5) on: Thu Jul 17 04:31:51 2014
# Project:  KeyCoin-qt - Copy (2) - Copy.pro
# Template: app
# Command: e:/deps/qt/4.8.5/bin/qmake.exe -o Makefile "KeyCoin-qt - Copy (2) - Copy.pro"
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = e:/deps/qt/4.8.5/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: KeyCoin-qt\ -\ Copy\ (2)\ -\ Copy.pro  e:/deps/qt/4.8.5/mkspecs/default/qmake.conf e:/deps/qt/4.8.5/mkspecs/features/device_config.prf \
		e:/deps/qt/4.8.5/mkspecs/qconfig.pri \
		e:/deps/qt/4.8.5/mkspecs/features/qt_functions.prf \
		e:/deps/qt/4.8.5/mkspecs/features/qt_config.prf \
		e:/deps/qt/4.8.5/mkspecs/win32-g++/qmake.conf \
		e:/deps/qt/4.8.5/mkspecs/features/exclusive_builds.prf \
		e:/deps/qt/4.8.5/mkspecs/features/default_pre.prf \
		e:/deps/qt/4.8.5/mkspecs/features/win32/default_pre.prf \
		e:/deps/qt/4.8.5/mkspecs/features/release.prf \
		e:/deps/qt/4.8.5/mkspecs/features/debug_and_release.prf \
		e:/deps/qt/4.8.5/mkspecs/features/default_post.prf \
		e:/deps/qt/4.8.5/mkspecs/features/win32/default_post.prf \
		e:/deps/qt/4.8.5/mkspecs/features/static.prf \
		e:/deps/qt/4.8.5/mkspecs/features/win32/thread.prf \
		e:/deps/qt/4.8.5/mkspecs/features/win32/rtti.prf \
		e:/deps/qt/4.8.5/mkspecs/features/win32/exceptions.prf \
		e:/deps/qt/4.8.5/mkspecs/features/win32/stl.prf \
		e:/deps/qt/4.8.5/mkspecs/features/warn_on.prf \
		e:/deps/qt/4.8.5/mkspecs/features/qt.prf \
		e:/deps/qt/4.8.5/mkspecs/features/moc.prf \
		e:/deps/qt/4.8.5/mkspecs/features/win32/windows.prf \
		e:/deps/qt/4.8.5/mkspecs/features/resources.prf \
		e:/deps/qt/4.8.5/mkspecs/features/uic.prf \
		e:/deps/qt/4.8.5/mkspecs/features/yacc.prf \
		e:/deps/qt/4.8.5/mkspecs/features/lex.prf \
		e:/deps/qt/4.8.5/lib/qtmain.prl \
		e:/deps/qt/4.8.5/lib/QtGui.prl \
		e:/deps/qt/4.8.5/lib/QtCore.prl
	$(QMAKE) -o Makefile "KeyCoin-qt - Copy (2) - Copy.pro"
e:/deps/qt/4.8.5/mkspecs/features/device_config.prf:
e:/deps/qt/4.8.5/mkspecs/qconfig.pri:
e:/deps/qt/4.8.5/mkspecs/features/qt_functions.prf:
e:/deps/qt/4.8.5/mkspecs/features/qt_config.prf:
e:/deps/qt/4.8.5/mkspecs/win32-g++/qmake.conf:
e:/deps/qt/4.8.5/mkspecs/features/exclusive_builds.prf:
e:/deps/qt/4.8.5/mkspecs/features/default_pre.prf:
e:/deps/qt/4.8.5/mkspecs/features/win32/default_pre.prf:
e:/deps/qt/4.8.5/mkspecs/features/release.prf:
e:/deps/qt/4.8.5/mkspecs/features/debug_and_release.prf:
e:/deps/qt/4.8.5/mkspecs/features/default_post.prf:
e:/deps/qt/4.8.5/mkspecs/features/win32/default_post.prf:
e:/deps/qt/4.8.5/mkspecs/features/static.prf:
e:/deps/qt/4.8.5/mkspecs/features/win32/thread.prf:
e:/deps/qt/4.8.5/mkspecs/features/win32/rtti.prf:
e:/deps/qt/4.8.5/mkspecs/features/win32/exceptions.prf:
e:/deps/qt/4.8.5/mkspecs/features/win32/stl.prf:
e:/deps/qt/4.8.5/mkspecs/features/warn_on.prf:
e:/deps/qt/4.8.5/mkspecs/features/qt.prf:
e:/deps/qt/4.8.5/mkspecs/features/moc.prf:
e:/deps/qt/4.8.5/mkspecs/features/win32/windows.prf:
e:/deps/qt/4.8.5/mkspecs/features/resources.prf:
e:/deps/qt/4.8.5/mkspecs/features/uic.prf:
e:/deps/qt/4.8.5/mkspecs/features/yacc.prf:
e:/deps/qt/4.8.5/mkspecs/features/lex.prf:
e:\deps\qt\4.8.5\lib\qtmain.prl:
e:\deps\qt\4.8.5\lib\QtGui.prl:
e:\deps\qt\4.8.5\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile "KeyCoin-qt - Copy (2) - Copy.pro"

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) F:/coins/keycoin/keycoin_july17/keycoin/src/leveldb/libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) F:/coins/keycoin/keycoin_july17/keycoin/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) $(MAKE)
	-$(DEL_FILE) clean
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

F:/coins/keycoin/keycoin_july17/keycoin/src/leveldb/libleveldb.a: FORCE

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
